In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
from  sklearn.datasets import make_classification

In [7]:
# create dataset
x,y = make_classification(n_samples=1000,n_features=10,n_classes=2, random_state=10)


In [12]:
x

array([[-1.00583777, -0.37653943, -0.62017967, ...,  1.67804613,
         1.0801799 ,  0.35358714],
       [ 0.41117999,  0.76240872, -0.78421   , ..., -0.85044853,
        -0.46130068,  1.06223729],
       [-1.52540752,  2.22793382,  0.5477266 , ...,  2.44004248,
         1.69891857, -0.70530243],
       ...,
       [-1.614926  ,  0.74310266,  1.13675653, ...,  2.8471565 ,
        -0.91145218, -1.22062837],
       [-0.14262151, -1.43323743, -2.54920034, ...,  0.39777869,
        -0.71639987,  0.6122551 ],
       [-0.1251796 ,  0.73011191, -1.87888552, ...,  0.74154153,
         0.30886522, -1.36966537]])

In [13]:
  from sklearn.model_selection import train_test_split
  x_train,x_test,y_train,y_test = train_test_split(x,y,test_size=0.2,random_state=10)

In [14]:
from sklearn.linear_model import LogisticRegression

In [15]:
logistic= LogisticRegression()
logistic.fit(x_train,y_train)
y_pred=logistic.predict(x_test)
y_pred

array([1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 0,
       1, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 1, 0, 0,
       0, 0, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 0,
       1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1,
       0, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1,
       0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 1, 0, 0, 1,
       1, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 1,
       0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 1,
       1, 1])

In [16]:
from sklearn.metrics import accuracy_score, confusion_matrix,classification_report

In [18]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.86      0.82      0.84        98
           1       0.83      0.87      0.85       102

    accuracy                           0.84       200
   macro avg       0.85      0.84      0.84       200
weighted avg       0.85      0.84      0.84       200



In [19]:
confusion_matrix(y_test,y_pred)

array([[80, 18],
       [13, 89]])